"""Add DashboardSettings model

Revision ID: dcdde5987c5f
Revises: 1164e037907f
Create Date: 2026-01-31 17:18:36.124096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcdde5987c5f'
down_revision = '1164e037907f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_table('behaviors')
    op.drop_table('accounts_rewardcodes')
    op.drop_table('migration_history')
    op.drop_table('player_cheat_detections')
    op.drop_table('ignore_list')
    op.drop_table('ugc_modular_build')
    op.drop_constraint('activity_log_ibfk_1', 'activity_log', type_='foreignkey')
    op.create_foreign_key(None, 'activity_log', 'charinfo', ['character_id'], ['id'], ondelete='CASCADE')
    op.alter_column('bug_reports', 'reporter_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
    op.drop_index('name', table_name='charinfo')
    op.drop_constraint('charinfo_ibfk_1', 'charinfo', type_='foreignkey')
    op.create_foreign_key(None, 'charinfo', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('charxml_ibfk_1', 'charxml', type_='foreignkey')
    op.drop_constraint('command_log_ibfk_1', 'command_log', type_='foreignkey')
    op.create_foreign_key(None, 'command_log', 'charinfo', ['character_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('friends_ibfk_1', 'friends', type_='foreignkey')
    op.drop_constraint('friends_ibfk_2', 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'charinfo', ['friend_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'friends', 'charinfo', ['player_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('leaderboard_ibfk_1', 'leaderboard', type_='foreignkey')
    op.create_foreign_key(None, 'leaderboard', 'charinfo', ['character_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('mail_ibfk_1', 'mail', type_='foreignkey')
    op.create_foreign_key(None, 'mail', 'charinfo', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('properties_ibfk_1', 'properties', type_='foreignkey')
    op.drop_constraint('properties_ibfk_2', 'properties', type_='foreignkey')
    op.create_foreign_key(None, 'properties', 'charinfo', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'properties', 'charinfo', ['clone_id'], ['prop_clone_id'], ondelete='CASCADE')
    op.drop_constraint('properties_contents_ibfk_1', 'properties_contents', type_='foreignkey')
    op.drop_constraint('properties_contents_ibfk_2', 'properties_contents', type_='foreignkey')
    op.create_foreign_key(None, 'properties_contents', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'properties_contents', 'ugc', ['ugc_id'], ['id'], ondelete='CASCADE')
    op.drop_column('servers', 'master_password')
    op.drop_constraint('ugc_ibfk_1', 'ugc', type_='foreignkey')
    op.drop_constraint('ugc_ibfk_2', 'ugc', type_='foreignkey')
    op.create_foreign_key(None, 'ugc', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ugc', 'charinfo', ['character_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ugc', type_='foreignkey')
    op.drop_constraint(None, 'ugc', type_='foreignkey')
    op.create_foreign_key('ugc_ibfk_2', 'ugc', 'charinfo', ['character_id'], ['id'])
    op.create_foreign_key('ugc_ibfk_1', 'ugc', 'accounts', ['account_id'], ['id'])
    op.add_column('servers', sa.Column('master_password', mysql.TEXT(), server_default=sa.text("'3.25 DARKFLAME1'"), nullable=False))
    op.drop_constraint(None, 'properties_contents', type_='foreignkey')
    op.drop_constraint(None, 'properties_contents', type_='foreignkey')
    op.create_foreign_key('properties_contents_ibfk_2', 'properties_contents', 'ugc', ['ugc_id'], ['id'])
    op.create_foreign_key('properties_contents_ibfk_1', 'properties_contents', 'properties', ['property_id'], ['id'])
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.create_foreign_key('properties_ibfk_2', 'properties', 'charinfo', ['clone_id'], ['prop_clone_id'])
    op.create_foreign_key('properties_ibfk_1', 'properties', 'charinfo', ['owner_id'], ['id'])
    op.drop_constraint(None, 'mail', type_='foreignkey')
    op.create_foreign_key('mail_ibfk_1', 'mail', 'charinfo', ['receiver_id'], ['id'])
    op.drop_constraint(None, 'leaderboard', type_='foreignkey')
    op.create_foreign_key('leaderboard_ibfk_1', 'leaderboard', 'charinfo', ['character_id'], ['id'])
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key('friends_ibfk_2', 'friends', 'charinfo', ['friend_id'], ['id'])
    op.create_foreign_key('friends_ibfk_1', 'friends', 'charinfo', ['player_id'], ['id'])
    op.drop_constraint(None, 'command_log', type_='foreignkey')
    op.create_foreign_key('command_log_ibfk_1', 'command_log', 'charinfo', ['character_id'], ['id'])
    op.create_foreign_key('charxml_ibfk_1', 'charxml', 'charinfo', ['id'], ['id'])
    op.drop_constraint(None, 'charinfo', type_='foreignkey')
    op.create_foreign_key('charinfo_ibfk_1', 'charinfo', 'accounts', ['account_id'], ['id'])
    op.create_index('name', 'charinfo', ['name'], unique=False)
    op.alter_column('bug_reports', 'reporter_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
    op.drop_constraint(None, 'activity_log', type_='foreignkey')
    op.create_foreign_key('activity_log_ibfk_1', 'activity_log', 'charinfo', ['character_id'], ['id'])
    op.create_table('ugc_modular_build',
    sa.Column('ugc_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('character_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('ldf_config', mysql.VARCHAR(length=60), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['charinfo.id'], name='ugc_modular_build_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ugc_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ignore_list',
    sa.Column('player_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('ignored_player_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ignored_player_id'], ['charinfo.id'], name='ignore_list_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['charinfo.id'], name='ignore_list_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'ignored_player_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('player_cheat_detections',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=False),
    sa.Column('violation_msg', mysql.TEXT(), nullable=False),
    sa.Column('violation_time', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('violation_system_address', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='player_cheat_detections_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('migration_history',
    sa.Column('name', mysql.TEXT(), nullable=False),
    sa.Column('date', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('accounts_rewardcodes',
    sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('rewardcode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='accounts_rewardcodes_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'rewardcode'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('behaviors',
    sa.Column('behavior_info', mysql.LONGTEXT(), nullable=True),
    sa.Column('character_id', mysql.BIGINT(display_width=20), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('behavior_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('behavior_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('dashboard_settings')
    # ### end Alembic commands ###
